---
- name: NTP instalation
  hosts: servers
  tasks: 
    - name: Ensure NTP is installed
      ansible.builtin.yum:
        name: chrony
        state: latest
      become: true
      when: ansible_distribution == "CentOS"
      
    - name: Ensure NTP is installed
      ansible.builtin.apt:
        name: ntp
        state: latest
      become: true
      when: ansible_distribution == "Ubuntu"
